In [2]:
import numpy as np

## Q1. [5 points]

Suppose we want to generate the following array:
array([1., 1.4, 1.8])


(1) Use `np.array` function to perform the task

(2) Use `np.arange` function to perform the task

(3) Use `np.linspace` function to perform the task

(4) Use `np.empty` and then substitute the element values to perform the task

       


In [3]:
#np.array 
np.array([1., 1.4, 1.8])

array([1. , 1.4, 1.8])

In [4]:
#np.arange
np.arange(start=1, stop=2, step=.4)

array([1. , 1.4, 1.8])

In [5]:
#np.linspace
np.linspace(start=1,stop=1.8,num=3)

array([1. , 1.4, 1.8])

In [6]:
#np.empty
np.empty(3)[0] = 1.
np.empty(3)[1] = 1.4
np.empty(3)[2] = 1.8
np.empty(3)

array([1. , 1.4, 1.8])

## Q2. [10 points]

Produce the following sequence

A1=[7.0, 6.9, 6.8, 6.7, ..., 0.0]

A2=[2.5, 2.6, 2.7, 2.8, ..., 9.5]

Both A1 and A2 have 71 elements. 

* Use Boolean arrays to report $x$ values that satisfy both following conditions. 

> * A1[x]>A2[x] 
> * A2[x]/2>1.5 

* Report the elements in A1 corresponding to these $x$ values
* These elements each have two indices (one negative and one non-negative). Report the negative one for each element from the previous step. 

In [7]:
A1 = np.linspace(start=7, stop=0, num=71)
A1

array([7. , 6.9, 6.8, 6.7, 6.6, 6.5, 6.4, 6.3, 6.2, 6.1, 6. , 5.9, 5.8,
       5.7, 5.6, 5.5, 5.4, 5.3, 5.2, 5.1, 5. , 4.9, 4.8, 4.7, 4.6, 4.5,
       4.4, 4.3, 4.2, 4.1, 4. , 3.9, 3.8, 3.7, 3.6, 3.5, 3.4, 3.3, 3.2,
       3.1, 3. , 2.9, 2.8, 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2. , 1.9,
       1.8, 1.7, 1.6, 1.5, 1.4, 1.3, 1.2, 1.1, 1. , 0.9, 0.8, 0.7, 0.6,
       0.5, 0.4, 0.3, 0.2, 0.1, 0. ])

In [8]:
A2 = np.linspace(start=2.5, stop=9.5, num=71)
A2

array([2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7,
       3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. ,
       5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3,
       6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6,
       7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9,
       9. , 9.1, 9.2, 9.3, 9.4, 9.5])

In [9]:
Bool_1 = A1 > A2 
Bool_2 = A2/2 > 1.5
indices_A1 = np.arange(0, 71)
indices_A1 = indices_A1[Bool_1 * Bool_2]
print("x-indices =", indices_A1)

x-indices = [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]


In [10]:
print("x =", A1[indices_A1])

x = [6.4 6.3 6.2 6.1 6.  5.9 5.8 5.7 5.6 5.5 5.4 5.3 5.2 5.1 5.  4.9 4.8]


In [11]:
print("negative x-indices = ",indices_A1 - 71)

negative x-indices =  [-65 -64 -63 -62 -61 -60 -59 -58 -57 -56 -55 -54 -53 -52 -51 -50 -49]
